const fs = require('fs');
let c = fs.readFileSync('C:/dev/ai/frontend/pages/schema.vue', 'utf8').split('\n');
c.splice(142, 60,
  '      <!-- Field Mappings (Only show in Edit mode because we need fields) -->',
  '      <div v-if="isEditMode" style="margin-top: 1rem; border-top: 1px solid #eee; padding-top: 1rem;">',
  '        <div style="margin-bottom: 0.5rem; font-weight: bold; font-size: 0.9rem; color: #666;">Domain Field Mappings (Required)</div>',
  '        <va-select',
  '          v-model="newDomain.identifierFieldId"',
  '          :options="domainFieldOptions"',
  '          value-by="value"',
  '          text-by="text"',
  '          label="Identifier Field (ID)*"',
  '          class="mb-4 w-full"',
  '          :error="mappingError.id"',
  '          :error-messages="[\'Required\']"',
  '        />',
  '        <va-select',
  '          v-model="newDomain.displayNameFieldId"',
  '          :options="domainFieldOptions.filter(o => o.type === \'MULTILINGUAL\')"',
  '          value-by="value"',
  '          text-by="text"',
  '          label="Display Name Field*"',
  '          class="mb-4 w-full"',
  '          :error="mappingError.name"',
  '          :error-messages="[\'Required\']"',
  '        />',
  '        <va-select',
  '          v-model="newDomain.descriptionFieldId"',
  '          :options="domainFieldOptions"',
  '          value-by="value"',
  '          text-by="text"',
  '          label="Description Field (Optional)"',
  '          class="mb-4 w-full"',
  '          clearable',
  '        />',
  '      </div>'
);
fs.writeFileSync('C:/dev/ai/frontend/pages/schema.vue', c.join('\n'));
console.log("Done");
