package com.classification.domain_system.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
public enum ErrorCode {

    // Common / Standard Status
    INVALID_INPUT(HttpStatus.BAD_REQUEST, "INVALID_INPUT"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "RESOURCE_NOT_FOUND"),
    ACCESS_DENIED(HttpStatus.FORBIDDEN, "ACCESS_DENIED"),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_SERVER_ERROR"),

    // Business Specific Errors
    DOMAIN_MISSING_FIELD_MAPPING(HttpStatus.BAD_REQUEST, "DOMAIN_MISSING_FIELD_MAPPING"),
    DATA_QUALITY_CHECK_FAILED(HttpStatus.BAD_REQUEST, "DATA_QUALITY_CHECK_FAILED"),
    DEDUPLICATION_FAILED(HttpStatus.BAD_REQUEST, "DEDUPLICATION_FAILED"),
    UPDATE_PENDING_CREATION(HttpStatus.BAD_REQUEST, "UPDATE_PENDING_CREATION"),
    UPDATE_PENDING_UPDATE(HttpStatus.BAD_REQUEST, "UPDATE_PENDING_UPDATE"),
    DELETE_PENDING_CREATION(HttpStatus.BAD_REQUEST, "DELETE_PENDING_CREATION"),
    NOT_STEP_ASSIGNEE(HttpStatus.FORBIDDEN, "NOT_STEP_ASSIGNEE"),
    STEP_NOT_PENDING(HttpStatus.BAD_REQUEST, "STEP_NOT_PENDING"),
    USERNAME_ALREADY_EXISTS(HttpStatus.BAD_REQUEST, "USERNAME_ALREADY_EXISTS"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    NODE_DOMAIN_MISMATCH(HttpStatus.BAD_REQUEST, "NODE_DOMAIN_MISMATCH"),
    FIELD_NODE_MISMATCH(HttpStatus.BAD_REQUEST, "FIELD_NODE_MISMATCH"),
    FIELD_DOMAIN_MISMATCH(HttpStatus.BAD_REQUEST, "FIELD_DOMAIN_MISMATCH"),
    SECTOR_DOMAIN_MISMATCH(HttpStatus.BAD_REQUEST, "SECTOR_DOMAIN_MISMATCH"),
    UPLOAD_DIR_FAIL(HttpStatus.INTERNAL_SERVER_ERROR, "UPLOAD_DIR_FAIL"),
    UPLOAD_FILE_FAIL(HttpStatus.INTERNAL_SERVER_ERROR, "UPLOAD_FILE_FAIL");

    private final HttpStatus status;
    private final String code;

    ErrorCode(HttpStatus status, String code) {
        this.status = status;
        this.code = code;
    }
}
