spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/domain_system
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

logging:
  level:
    com.classification.domain_system.integration.DataMappingTransformer: DEBUG
